### ISSUE TITLE
Data Channel authentication technologies

### ISSUE THREAD

**Issue by castroflavio** [scistream/scistream-proto#30]
Are there alternatives to Stunnel?

Should we explore L3 tunnels such as VPNs and Wireguard?

We don't know if they would perform better.

**Comment by JoaquinChung** [comment]
Would this be L3 tunnels in software?

**Comment by castroflavio** [comment]
Yes. But I'm pretty sure, L3 tunnels can also be implemented in hardware at wire-speeds.
